[package]
name = "mining-bot"
version = "0.0.1"
authors = ["Gavin Gao <gavin@blockstack.com>","Ludo Galabru <ludovic@blockstack.com>"]
edition = "2018"

[dependencies]
lazy_static = "1.4.0"
pico-args = "0.3.1"
rand = "=0.7.2"
secp256k1 = { version = "0.11.5" }
serde = "1"
serde_derive = "1"
serde_json = { version = "1.0", features = ["arbitrary_precision", "raw_value"] }
stacks = { package = "blockstack-core", path = "../../." }
toml = "0.5.6"
async-h1 = "=1.0"
async-std = { version = "<1.6", features = ["attributes"] }
http-types = "1.0"
base64 = "0.12.0"

[dev-dependencies]
warp = "0.2"
tokio = "0.2.21"
reqwest = { version = "0.10", features = ["blocking", "json", "rustls"] }

[[bin]]
name = "mining-bot"
path = "src/main.rs"

[features]
monitoring_prom = ["stacks/monitoring_prom"]
default = []
