global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['127.0.0.1:9090']
  - job_name: 'stacks-node-leader'
    static_configs:
    - targets: ['127.0.0.1:4000']
  - job_name: 'stacks-node-follower'
    static_configs:
    - targets: ['127.0.0.1:5000']
