name: Run bitcoind/stacks-node integration tests

on: pull_request

jobs:
  bitcoin-test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel prior runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Run bitcoin tests as a docker script
        env:
          DOCKER_BUILDKIT: 1
        run: docker build -f ./.github/actions/bitcoin-int-tests/Dockerfile.bitcoin-tests .
