name: Deploy

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:      
  dist:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform: [ windows-x64, macos-x64, linux-x64, linux-musl-x64, linux-armv7, linux-arm64 ]

    steps:
      - name: Cancel prior runs
        uses: styfle/cancel-workflow-action@0.4.1
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v2

      - name: Build distributable
        env:
          DIST_TARGET_FILTER: ${{ matrix.platform }}
        run: build-scripts/build-dist.sh

      - name: Upload artifact
        # Only upload the artifacts if we're actually pushed to master
        if: ${{ github.event_name == 'push' }}
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.platform }}
          path: dist/
